export const ABOUT_CONTENT = {
  es: {
    eyebrow: 'IMMERSO + GIRASOMNIS',
    title: 'ABOUT',
    lead: 'DISEÑAMOS EXPERIENCIAS INMERSIVAS DONDE CREATIVIDAD, TECNOLOGÍA Y LENGUAJE VISUAL SE UNEN PARA CREAR IMPACTO REAL.',
    body: 'EVENTOS INMERSIVOS, TECNOLOGÍA AUDIOVISUAL, ENTORNOS DIGITALES, PIEZAS VISUALES Y EXPERIENCIAS HÍBRIDAS CON UNA DIRECCIÓN ARTÍSTICA CLARA Y PRECISIÓN TÉCNICA.',
    contact: 'CONTACTO'
  },
  en: {
    eyebrow: 'IMMERSO + GIRASOMNIS',
    title: 'ABOUT',
    lead: 'WE DESIGN IMMERSIVE EXPERIENCES WHERE CREATIVITY, TECHNOLOGY AND VISUAL LANGUAGE COME TOGETHER TO CREATE REAL IMPACT.',
    body: 'IMMERSIVE EVENTS, AUDIOVISUAL TECHNOLOGY, DIGITAL ENVIRONMENTS, VISUAL PIECES AND HYBRID EXPERIENCES SHAPED WITH CLEAR ART DIRECTION AND TECHNICAL PRECISION.',
    contact: 'CONTACT'
  }
};