export const ZONES = [
  {
    id: 'software',
    label: 'SOFTWARE HUB',
    title: 'Software & Tech',
    description: 'Desarrollamos software a medida, apps web, plataformas SaaS y soluciones digitales que transforman tu negocio.',
    position: [20, 0, -20],
    color: 0x00ffff,
    colorHex: '#00ffff',
    darkColor: 0x001a1a,
    radius: 7,
    buildingHeight: 18,
    buildingWidth: 8,
    icon: '💻',
    services: ['Apps Web & Móvil', 'Plataformas SaaS', 'E-commerce', 'Integraciones API'],
    cta: 'Ver Proyectos Software',
  },
  {
    id: 'video',
    label: 'STUDIO 360',
    title: 'Video & Producción',
    description: 'Producción audiovisual de alto impacto: spots, documentales, contenido viral y transmisiones en vivo 360°.',
    position: [-20, 0, -20],
    color: 0xff00ff,
    colorHex: '#ff00ff',
    darkColor: 0x1a001a,
    radius: 7,
    buildingHeight: 20,
    buildingWidth: 9,
    icon: '🎬',
    services: ['Spots Publicitarios', 'Video 360°', 'Live Streaming', 'Motion Graphics'],
    cta: 'Ver Producciones',
  },
  {
    id: 'avatars',
    label: 'AVATAR LAB',
    title: 'Avatares 3D & XR',
    description: 'Creamos avatares 3D hiperrealistas, experiencias de realidad aumentada y mundos virtuales inmersivos.',
    position: [20, 0, 20],
    color: 0xffff00,
    colorHex: '#ffff00',
    darkColor: 0x1a1a00,
    radius: 7,
    buildingHeight: 16,
    buildingWidth: 7,
    icon: '🤖',
    services: ['Avatares 3D', 'AR/VR Experiences', 'Metaverso', 'NFT & Digital Assets'],
    cta: 'Explorar Avatares',
  },
  {
    id: 'events',
    label: 'EVENT DOME',
    title: 'Eventos Inmersivos',
    description: 'Diseñamos y producimos eventos únicos: shows de mapping, instalaciones interactivas, festivales y experiencias físico-digitales.',
    position: [-20, 0, 20],
    color: 0xff6600,
    colorHex: '#ff6600',
    darkColor: 0x1a0800,
    radius: 7,
    buildingHeight: 14,
    buildingWidth: 10,
    icon: '🎭',
    services: ['Mapping & Proyecciones', 'Instalaciones Interactivas', 'Festivales Digitales', 'Eventos Corporativos XR'],
    cta: 'Ver Eventos',
  },
  {
    id: 'contact',
    label: 'HQ AGENCY360',
    title: 'Agencia 360',
    description: 'Somos tu socio creativo y tecnológico. Hablemos sobre tu próximo proyecto y cómo podemos llevarlo al siguiente nivel.',
    position: [0, 0, -5],
    color: 0x0088ff,
    colorHex: '#0088ff',
    darkColor: 0x000a1a,
    radius: 6,
    buildingHeight: 25,
    buildingWidth: 10,
    icon: '🏢',
    services: ['Consultoría 360', 'Estrategia Digital', 'Branding', 'Producción Integral'],
    cta: 'Contactar Ahora',
    isHQ: true,
  },
];