export const STANDS = [
  {
    id: 'horizons',
    key: 'H',
    position: [-20, 0, -14],
    color: '#00c8ff',
    colorInt: 0x00c8ff,
    title: 'SHOW HORIZONS',
    subtitle: 'Danza y Visuales Inmersivos · Temática Marina',
    description: 'Un viaje escénico inspirado en el universo marino, donde danza y visuales inmersivos se unen para hablar de amplitud, transformación y movimiento. Ideal para galas y eventos especiales.',
    tags: ['DANZA', 'INMERSIVO', 'MARINA', 'GALA'],
    icon: '🌊',
    type: 'video',
    videoUrl: 'https://www.youtube.com/embed/slzh4Z0k1qw?autoplay=1&loop=1&playlist=slzh4Z0k1qw&rel=0&modestbranding=1',
    videoThumb: 'https://img.youtube.com/vi/slzh4Z0k1qw/maxresdefault.jpg',
  },
  {
    id: 'lumina',
    key: 'L',
    position: [20, 0, 14],
    color: '#ff00ff',
    colorInt: 0xff00ff,
    title: 'SHOW LUMINA',
    subtitle: 'Danza Visual, Luz y Efectos Digitales para Eventos Premium',
    description: 'Una pieza escénica donde movimiento, luz y efectos digitales se fusionan para crear una experiencia vibrante y contemporánea. Elegante, tecnológica e inmersiva.',
    tags: ['DANZA', 'LUZ', 'DIGITAL', 'GALA'],
    icon: '✨',
    type: 'video',
    videoUrl: 'https://www.youtube.com/embed/vFhWqC72e9k?autoplay=1&loop=1&playlist=vFhWqC72e9k&rel=0&modestbranding=1',
    videoThumb: 'https://img.youtube.com/vi/vFhWqC72e9k/maxresdefault.jpg',
  },
  {
    id: 'genesis_lux',
    key: 'G',
    position: [20, 0, -14],
    color: '#ffaa00',
    colorInt: 0xffaa00,
    title: 'GENESIS LUX',
    subtitle: 'Beta Teaser · Danza, Violín en Vivo y Luz',
    description: 'Una performance visual inmersiva donde la danza contemporánea, el violín en vivo, la luz y la atmósfera se unen en una experiencia escénica elegante y emotiva.',
    tags: ['DANZA', 'VIOLÍN', 'LUZ', 'PREMIUM'],
    icon: '🎻',
    type: 'video',
    videoUrl: 'https://www.youtube.com/embed/h7LhhrhjvAE?autoplay=1&loop=1&playlist=h7LhhrhjvAE&rel=0&modestbranding=1',
    videoThumb: 'https://img.youtube.com/vi/h7LhhrhjvAE/maxresdefault.jpg',
  },
  {
    id: 'lidar',
    key: 'I',
    position: [0, 0, 20],
    color: '#00ff88',
    colorInt: 0x00ff88,
    title: 'REEL LIDAR',
    subtitle: 'Instalación Interactiva · Última Generación',
    description: 'Experiencia interactiva con tecnología LiDAR que convierte el movimiento del público en arte en tiempo real. Alto impacto para espacios culturales y corporativos.',
    tags: ['LIDAR', 'INTERACTIVO', 'ARTE', 'TECH'],
    icon: '📡',
    type: 'showcase',
    showcaseItems: [
      { img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', label: 'LiDAR Tech', desc: 'Tecnología de última generación' },
      { img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80', label: 'Arte Interactivo', desc: 'El movimiento del público crea arte' },
      { img: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80', label: 'Alto Impacto', desc: 'Para espacios culturales y corporativos' },
    ],
  },
  {
    id: 'mariposas',
    key: 'M',
    position: [-20, 0, 14],
    color: '#ff44cc',
    colorInt: 0xff44cc,
    title: 'MARIPOSAS BIÓNICAS',
    subtitle: 'Show de Mariposas con Tecnología LED y Biomimética',
    description: 'Un espectáculo único donde bailarines con alas de mariposa LED crean un efecto visual hipnótico y etéreo. Perfecto para eventos de marca, openings y momentos de gran impacto visual.',
    tags: ['LED', 'MARIPOSAS', 'BIOMIMÉTICA', 'SHOW'],
    icon: '🦋',
    type: 'showcase',
    showcaseItems: [
      { img: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80', label: 'Alas LED', desc: 'Bailarines con alas de mariposa LED' },
      { img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80', label: 'Biomimética', desc: 'Inspirado en la naturaleza' },
      { img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80', label: 'Alto Impacto', desc: 'Para openings y eventos de marca' },
    ],
  },
  {
    id: 'viky',
    key: 'V',
    position: [0, 0, -12],
    color: '#7c3aed',
    colorInt: 0x7c3aed,
    title: 'VIKY · AVATAR IA',
    subtitle: 'Avatar Interactivo con IA · 57 Idiomas en Tiempo Real',
    description: 'VIKY es nuestro avatar interactivo impulsado por IA. 57 idiomas en tiempo real, reconocimiento de voz continuo, lipsync, expresiones faciales y memoria de sesión.',
    tags: ['IA', 'AVATAR', '57 IDIOMAS', 'EVENTOS'],
    icon: '🤖',
    type: 'video',
    videoUrl: 'https://www.youtube.com/embed/W0EKcrfuCL8?autoplay=1&loop=1&playlist=W0EKcrfuCL8&rel=0&modestbranding=1',
    videoThumb: 'https://img.youtube.com/vi/W0EKcrfuCL8/maxresdefault.jpg',
  },
  {
    id: 'show_vivo',
    key: 'C',
    position: [12, 0, -20],
    color: '#ff4422',
    colorInt: 0xff4422,
    title: 'SHOW VIVO 360',
    subtitle: 'Producción en Directo · Video Mapping y Escena',
    description: 'Producción audiovisual en directo con video mapping, escenografía digital y dirección artística de alto impacto. Creamos experiencias únicas para eventos, galas y presentaciones especiales.',
    tags: ['VIDEO', 'DIRECTO', 'MAPPING', 'PRODUCCIÓN'],
    icon: '🎬',
    type: 'video',
    videoUrl: 'https://drive.google.com/file/d/1cavAPSpd7OhMqfUroTdoDrmyLjskjg5f/preview',
  },
  {
    id: 'evento_digital',
    key: 'D',
    position: [-12, 0, -20],
    color: '#4488ff',
    colorInt: 0x4488ff,
    title: 'EVENTO DIGITAL',
    subtitle: 'Experiencia Visual Interactiva · 360°',
    description: 'Concepto audiovisual digital de última generación. Combinamos tecnología, arte y narrativa para crear eventos memorables con identidad propia y alto componente visual inmersivo.',
    tags: ['DIGITAL', 'INTERACTIVO', '360°', 'XR'],
    icon: '🌐',
    type: 'video',
    videoUrl: 'https://drive.google.com/file/d/1NzwqlJdLu--yJGxo7uscMbRoF71JFC1K/preview',
  },
  {
    id: 'arcade_nexus',
    key: 'P',
    position: [-8, 0, 2],
    color: '#00ffff',
    colorInt: 0x00ffff,
    title: 'NEXUS PLAY',
    subtitle: 'Arcade · Snake · Pong · Breakout',
    description: 'Una máquina arcade dentro de la ciudad. Acércate, pulsa Play y entra en una vista frontal para jugar tres clásicos.',
    tags: ['ARCADE', 'SNAKE', 'PONG', 'BREAKOUT'],
    icon: '🕹️',
    type: 'arcade',
  },
  {
    id: 'arcade_beta',
    key: 'Q',
    position: [8, 0, 2],
    color: '#ff44cc',
    colorInt: 0xff44cc,
    title: 'BETA PLAY',
    subtitle: 'Arcade · Snake · Pong · Breakout',
    description: 'Segunda máquina arcade en la plaza. Compite y supera tu puntuación en los tres clásicos del arcade.',
    tags: ['ARCADE', 'SNAKE', 'PONG', 'BREAKOUT'],
    icon: '🕹️',
    type: 'arcade',
  },
  {
    id: 'arcade_sigma',
    key: 'R',
    position: [0, 0, 9],
    color: '#ffaa00',
    colorInt: 0xffaa00,
    title: 'SIGMA PLAY',
    subtitle: 'Arcade · Snake · Pong · Breakout',
    description: 'Tercera máquina arcade en el corazón de la ciudad. Tres juegos clásicos con dificultad progresiva.',
    tags: ['ARCADE', 'SNAKE', 'PONG', 'BREAKOUT'],
    icon: '🕹️',
    type: 'arcade',
  },
];
