export const STANDS = [
  {
    id: 'back_to_life',
    key: 'B',
    position: [-20, 0, -14],
    color: '#ff00ff',
    colorInt: 0xff00ff,
    title: 'BACK TO LIFE',
    subtitle: 'Dance Mapping · Evento Corporativo',
    description: 'Un dance mapping con mucha energía ideal para un momento "fiesta" de un evento corporativo.',
    tags: ['MAPPING', 'DANZA', 'ENERGÍA', 'EVENTO CORP.'],
    icon: '🎉',
    type: 'video',
    videoUrl: 'https://player.vimeo.com/video/76979871?autoplay=1&loop=1&color=ff00ff&title=0&byline=0&portrait=0',
    videoThumb: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
  },
  {
    id: 'avatar_xr',
    key: 'A',
    position: [20, 0, 14],
    color: '#ffff00',
    colorInt: 0xffff00,
    title: 'AVATAR HIPERREALISTA',
    subtitle: 'XR · Metaverso · Presentación',
    description: 'Avatares 3D fotorrealistas para presentaciones corporativas, metaverso y experiencias XR de alto impacto.',
    tags: ['AVATAR 3D', 'XR', 'METAVERSO', 'PRESENTACIÓN'],
    icon: '🤖',
    type: 'showcase',
    showcaseItems: [
      { img: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=600&q=80', label: 'Avatar Corporativo', desc: 'Hiperrealismo total para presentaciones ejecutivas' },
      { img: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=600&q=80', label: 'Avatar Metaverso', desc: 'Identidad digital para mundos virtuales' },
      { img: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80', label: 'XR Experience', desc: 'Experiencias inmersivas con avatares personalizados' },
    ],
  },
  {
    id: 'software_demo',
    key: 'S',
    position: [20, 0, -14],
    color: '#00ffff',
    colorInt: 0x00ffff,
    title: 'SOFTWARE & APPS',
    subtitle: 'Desarrollo · SaaS · E-commerce',
    description: 'Plataformas digitales de alto impacto: apps web, móvil, e-commerce y SaaS a medida.',
    tags: ['WEB APP', 'MÓVIL', 'SAAS', 'E-COMMERCE'],
    icon: '💻',
    type: 'projects',
    projects: [
      { name: 'E-COMMERCE 360', cat: 'Tienda Online', color: '#00ffff', stats: ['↑ 340% ventas', '2.1M visitas/mes'], icon: '🛒' },
      { name: 'SAAS PLATFORM', cat: 'Plataforma B2B', color: '#00ffff', stats: ['500+ empresas', '99.9% uptime'], icon: '☁️' },
      { name: 'MOBILE XR APP', cat: 'App Móvil AR', color: '#00ffff', stats: ['4.9★ AppStore', '100K downloads'], icon: '📱' },
      { name: 'METAVERSE SDK', cat: 'Integración 3D', color: '#00ffff', stats: ['Open Source', '2M API calls/día'], icon: '🌐' },
    ],
  },
];